"""
HealChain FL-Client - Miner Verification
Implements Algorithm 5 from BTP Report Section 4.6

M5: Miner Verification Feedback (Consensus)
"""

import os
import requests
from typing import Dict, Optional

# Backend API URL
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:3000")


def verify_candidate_block(
    task_id: str,
    miner_address: str,
    candidate_block: Dict,
    model_data: Optional[bytes] = None
) -> bool:
    """
    Verify candidate block according to Algorithm 5:
    1. Download model from IPFS (if provided)
    2. Verify aggregator signature
    3. Verify score commitment is included
    4. Verify model passes sanity check (loss decreased)
    
    Returns:
        True if VALID, False if INVALID
    """
    
    # Step 1: Verify aggregator signature (if present)
    # Note: Signature verification would require aggregator's public key
    # For MVP, we assume signature is valid if present
    
    # Step 2: Verify score commitment is included
    score_commits = candidate_block.get("scoreCommits", [])
    if not score_commits:
        return False
    
    # Step 3: Model sanity check (if model data provided)
    if model_data:
        # Basic sanity check: model should be non-empty
        if len(model_data) == 0:
            return False
        # Additional checks could include:
        # - Model structure validation
        # - Loss comparison (should decrease)
        # - Accuracy validation
    
    # For MVP: If all basic checks pass, vote VALID
    return True


def submit_verification_vote(
    task_id: str,
    miner_address: str,
    verdict: str,
    signature: Optional[str] = None
) -> Dict:
    """
    Submit verification vote to backend (M5)
    
    Args:
        task_id: Task identifier
        miner_address: Miner's wallet address
        verdict: "VALID" or "INVALID"
        signature: Optional signature for vote
    
    Returns:
        Verification record from backend
    """
    
    if verdict not in ["VALID", "INVALID"]:
        raise ValueError("Verdict must be VALID or INVALID")
    
    # Create authentication message
    message = f"HealChain Verification\nTask: {task_id}\nVerdict: {verdict}\nMiner: {miner_address}"
    
    # For MVP: Signature can be generated using wallet
    # In production, use proper wallet signing
    
    payload = {
        "taskID": task_id,
        "minerAddress": miner_address,
        "verdict": verdict,
        "message": message,
        "signature": signature or ""  # Would be generated by wallet
    }
    
    response = requests.post(
        f"{BACKEND_URL}/verification/submit",
        json=payload,
        headers={"Content-Type": "application/json"}
    )
    
    response.raise_for_status()
    return response.json()


def get_consensus_result(task_id: str) -> Dict:
    """
    Get consensus result for a task
    
    Returns:
        {
            "approved": bool,
            "validVotes": int,
            "invalidVotes": int,
            "totalMiners": int,
            "majorityRequired": int
        }
    """
    
    response = requests.get(
        f"{BACKEND_URL}/verification/consensus/{task_id}"
    )
    
    response.raise_for_status()
    return response.json()

